FROM oven/bun:1.3-alpine AS base

WORKDIR /usr/src/app

RUN apk add --no-cache openssl

# Copy entire monorepo
COPY . .

# Install exactly from committed lockfile
RUN bun install --frozen-lockfile

# Generate Prisma Client
WORKDIR /usr/src/app/packages/db
RUN bun x prisma generate

# Start worker
WORKDIR /usr/src/app/apps/api

CMD ["bun", "run", "src/workers/submission.worker.ts"]
